### ISSUE TITLE
IR remote commands won’t work after updating to 0.6.0

### ISSUE THREAD

**Issue by Lars-** [JackJPowell/hass-unfoldedcircle#26]
**Describe the bug**
The remote commands won’t work. It simply says “unknown error”. In the logs, I found this:
```

Logger: homeassistant.components.websocket_api.http.connection
Bron: custom_components/unfoldedcircle/remote.py:85
integratie: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:52:50 (3 gebeurtenissen)
Laatst gelogd: 17:55:10

[140718812259776] Error handling message: Unknown error (unknown_error) Lars Jansen from 10.0.1.12 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1600, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 435, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 487, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 512, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 485, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 723, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/unfoldedcircle/remote.py", line 85, in async_send_command
    await self.coordinator.api.send_remote_command(
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 964, in send_remote_command
    body = {"codeset_id": ir_code.get("device_id"), "cmd_id": command}
                          ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'get' for 'dict' objects doesn't apply to a 'str' object

```

**To Reproduce**
Simply run the example from the readme (replacing the values with valid ones of course)

**Expected behavior**
No error

**Comment by JackJPowell** [comment]
I'll have this fixed soon. Sorry about the disruption.

**Comment by JackJPowell** [comment]
The latest release should correct this issue. Please reopen if you have any problems. Thanks @Lars-
