### ISSUE TITLE
Log full of errors when remote sleeps

### ISSUE THREAD

**Issue by mvdwetering** [JackJPowell/hass-unfoldedcircle#28]
**Describe the bug**

I was looking at my Home Assistant logs and noticed it was full of errors like below (2584 in about 4 days). The IP in the errors are from the UC remote, so I am guessing it is coming from this integration when the remote goes to sleep.

```
2024-03-20 21:15:54.008 INFO (MainThread) [websockets.client] ! connect failed again; retrying in 60 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 598, in __aiter__
    async with self as protocol:
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1120, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.178.50', 80)
```

**To Reproduce**
1. Put remote to sleep
2. Wait a while
3. Look at Home Assistant logs

**Expected behavior**

I understand an error when connection gets lost. Most integrations only give an error when it gets lost the first time and then not until connection gets restored.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 122.0.6261.112 

**Smartphone (please complete the following information):**
 - Device: n.a.
 - OS: n.a.
 - Browser n.a.
 - Version n.a.

**Additional context**

Home Assistant OS: 12.1
Home Assistant Core: 2024.3.1
Integration version: v0.6.2

**Comment by mvdwetering** [comment]
Yeah, that is the complete error. Which indeed is weird, so it is still only a guess it is this integration only based on the IP address in the message.

Ah, good point about the loglevel. I changed that to Info a long long time ago and totally forgot about that it was not at default anymore. That makes it easy to resolve.

So not really a problem then I guess.

**Comment by mvdwetering** [comment]
Since the problem is on my side because I enabled the additional logging I am closing it
