### ISSUE TITLE
Unable to setup integration on HA

### ISSUE THREAD

**Issue by davidclaeysquinones** [JackJPowell/hass-unfoldedcircle#29]
This is the error message I'm getting
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unfoldedcircle/__init__.py", line 52, in async_setup_entry
    await coordinator.api.init()
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 1213, in init
    await group
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 801, in get_remote_update_information
    self._next_update_check_date = information["next_check_date"]
```

Currently I'm on HA 2024.4.2 and version v0.6.3 of the integration (installed trough HACS).
I'm having this issue since a couple of versions and was hoping that it eventually would get sorted out.
I'm more than happy to give any additional information or try any quickfix.

**Comment by davidclaeysquinones** [comment]
I'm running on the stable release (1.7.7).

**Comment by JackJPowell** [comment]
Just pushed a small update that will hopefully resolve this problem.

**Comment by parkervcp** [comment]
I just want to add I am having an issue with adding my remote to my HA setup as well. I have recently updated my add-on for this and went to re-add my remote and its dock to my HA setup. 

Here is the full error. I am still getting used to Python and am reading through code to see if I can figure out what happened. 
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:433
First occurred: 8:49:35 AM (1 occurrences)
Last logged: 8:49:35 AM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unfoldedcircle/config_flow.py", line 257, in async_step_zeroconf_confirm
    info, self.api = await validate_input(self.hass, user_input, host)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unfoldedcircle/config_flow.py", line 103, in validate_input
    token_id = await remote.set_token_for_external_system(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 571, in set_token_for_external_system
    raise ExternalSystemNotRegistered
TypeError: ExternalSystemNotRegistered.__init__() missing 1 required positional argument: 'message'
```

**Comment by JackJPowell** [comment]
Hey @parkervcp. Sorry about the issue. You did discover a bug, but it's not the root cause of the problem. It's raising that exception (incorrectly) because something failed just a little earlier.

1) Did everything setup cleanly in the integration but you are seeing this stray error in the logs?
2) Likely doesn't matter, but what remote firmware are you running?

**Comment by parkervcp** [comment]
@JackJPowell Sorry I have been busy. I am willing to run whatever you need to identify things here. If I need to create a new issue for this I will.

**Comment by SpikeNbg** [comment]
Hi!

I've had the exact same error like parkervcp and couldn't configure my (newly purchased) Remote Two.

Here is a workaround that worked for me:

1. installed the version 0.10 of this integration via hacs 
2. configured my Remote Two without any problems
4. updated to 0.11 
5. configured my newly found Remote Two Dock
6. everythings seems to work

PS: Thanks for this integration!

**Comment by JackJPowell** [comment]
Hey, @parkervcp and @SpikeNbg 

I've been out of town so this took a little longer to get to than planned but I just pushed a beta release that will hopefully correct the problem you both ran into. If you are still having an issue Parker, give it a try. You can toggle beta releases in the hacs integration.

**Comment by parkervcp** [comment]
@JackJPowell That seems to have fixed it for me. Now if only my dock didn't take like 10 tries to re-sync with the remote sometimes.

**Comment by JackJPowell** [comment]
I'll push v0.12 out soon. Please open another issue if you are still having an issue.
