### ISSUE TITLE
Wake-on-LAN deactivation in Home Assistant fails

### ISSUE THREAD

**Issue by alsFC** [JackJPowell/hass-unfoldedcircle#60]
**Describe the bug**
Wake-on-LAN deactivation in Home Assistant fails.

**To Reproduce**
1. Enable Wake-on-LAN on the Remote
2. Disable the switch Wake-on-LAN in Home Assistant
3. An error occurs

**Expected behavior**
Wake-on-LAN is deactivated on the Remote

**Screenshots**
![image](https://github.com/user-attachments/assets/909a4af8-3b5b-4549-bcc0-3be8b729b646)

**Additional context**
Logs:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/unfoldedcircle/switch.py", line 274, in async_turn_off
    await self.entity_description.control_fn(self.coordinator, False)
  File "/config/custom_components/unfoldedcircle/switch.py", line 65, in update_remote_network_settings
    await coordinator.api.patch_remote_network_settings(wake_on_lan=enable)
  File "/usr/local/lib/python3.12/site-packages/pyUnfoldedCircleRemote/remote.py", line 1320, in patch_remote_network_settings
    if wake_on_lan is not None and self._sw_version >= 2:
                                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'str' and 'int'`

**Comment by JackJPowell** [comment]
Thanks for the report! This update should fix things. Be aware that there is a bug with the remote firmware that causes wifi to drop after disabling WOL.

https://github.com/JackJPowell/hass-unfoldedcircle/releases/tag/v0.13.1
